Added spatial bbox helper
facebookresearch/AugLy pull request #171
Opened 2021-12-08 15:07 UTC by membriux

## Summary
- [x] I have read CONTRIBUTING.md to understand how to contribute to this repository :)

Computes the bbox that encloses a white box in a black background for any augmentation.

### Image
```bash
python -m unittest discover -s augly/tests/image_tests/ -p "*_test.py"
# Or `python -m unittest discover -s augly/tests/image_tests/ -p "*.py"` to run pytorch test too (must install `torchvision` to run)
```
```
Ran 82 tests in 53.014s

OK (skipped=5)
```

## Other testing

Colab notebook testing the bbox helper → https://colab.research.google.com/drive/1g_0I6f_bv4Wsna6l9jjZrOJ62a4dpu8U#scrollTo=yUczCe6FU9Bs

2021-12-08 15:21 UTC, zpapakipos requested changes

2021-12-08 15:21 UTC, zpapakipos commented on augly/image/utils/bboxes.py
> +from typing import List, Optional, Tuple, Callable
```suggestion
from typing import Callable, List, Optional, Tuple
```
alphabetize

2021-12-08 15:21 UTC, zpapakipos commented on augly/image/utils/bboxes.py
> +    # channels is not 0 (i.e. the pixel at (x, y) is not black)
```suggestion
```

2021-12-08 15:21 UTC, zpapakipos commented on augly/image/utils/bboxes.py
> +    for any augmentation.
```suggestion
    Computes the bbox that encloses the transformed bbox in the image transformed by
    `aug_function`. This helper can be used to compute the transformed bbox for any
    augmentation which doesn't affect the color of the source image (e.g. any spatial
    augmentation).
```

2021-12-08 15:21 UTC, zpapakipos commented on augly/image/utils/bboxes.py
> +    dummy_image = create_test_image(w=src_w, h=src_h, bbox=bbox)
`create_test_image()` is not defined here. Please create `dummy_image` here using the code from `create_test_image()` in the notebook.

2021-12-08 15:21 UTC, zpapakipos commented on augly/image/utils/bboxes.py
> +
```suggestion
```

2021-12-08 15:36 UTC, zpapakipos commented on augly/image/utils/bboxes.py
> +from PIL import Image
```suggestion
from PIL import Image, ImageDraw
```

2021-12-08 15:44 UTC, zpapakipos commented on augly/image/utils/bboxes.py
> +    draw.rectangle([bbox[0] * w, bbox[1] * h, bbox[2] * w, bbox[3] * h], fill="white")
```suggestion
    dummy_image = Image.new("RGB", (src_w, src_h))
    draw = ImageDraw.Draw(image)
    draw.rectangle([bbox[0] * src_w, bbox[1] * src_h, bbox[2] * src_w, bbox[3] * src_h], fill="white")
```

2021-12-09 07:43 UTC, jbitton reviewed
overall lgtm! just three tiny comments on my end and we can land!

2021-12-09 07:43 UTC, jbitton commented on augly/image/utils/bboxes.py
>  import numpy as np
nit on grouping imports -- the first set of imports should only be imports from python (i.e. no external packages etc)
```suggestion
from typing import Callable, List, Optional, Tuple

import augly.image.utils as imutils
import numpy as np
from PIL import Image, ImageDraw
```

2021-12-09 07:43 UTC, jbitton commented on augly/image/utils/bboxes.py
> +        [bbox[0] * src_w, bbox[1] * src_h, bbox[2] * src_w, bbox[3] * src_h],
our internal linter errored with:
```
Incompatible parameter type [6]: Expected typing.Union[Tuple[Tuple[float, float], Tuple[float, float]], Tuple[float, float, float, float]] for 1st positional only parameter to call ImageDraw.ImageDraw.rectangle but got List[typing.Any].
```

Here's a potential way to fix this:
```suggestion
    bbox: Tuple[float, float, float, float],
    src_w: int,
    src_h: int,
    aug_function: Callable,
    **kwargs,
) -> Tuple:
    """
    Computes the bbox that encloses the transformed bbox in the image transformed by
    `aug_function`. This helper can be used to compute the transformed bbox for any
    augmentation which doesn't affect the color of the source image (e.g. any spatial
    augmentation).
    """
    dummy_image = Image.new("RGB", (src_w, src_h))
    draw = ImageDraw.Draw(dummy_image)
    draw.rectangle(
        (bbox[0] * src_w, bbox[1] * src_h, bbox[2] * src_w, bbox[3] * src_h),
```

This *should* help ensure that what's being passed into `draw.rectange` is in fact a `Tuple[float, float, float, float]`

2021-12-09 07:43 UTC, jbitton commented on augly/image/utils/bboxes.py
> +    return new_bbox
```suggestion
    return (min_x / aug_w, min_y / aug_h, max_x / aug_w, max_y / aug_h)
```

2021-12-09 17:24 UTC, zpapakipos approved these changes
Thanks for making all the requested changes!

2021-12-09 20:11 UTC, closed without merging